/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LinksRouteImport } from './routes/links'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as TermosDeServicoRouteImport } from './routes/termos-de-servico'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedCreatorRouteImport } from './routes/_authenticated/creator'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as MediakitIndexRouteImport } from './routes/mediakit.index'
import { Route as MediakitSlugRouteImport } from './routes/mediakit.$slug'
import { Route as PrivacyLangRouteImport } from './routes/privacy.$lang'
import { Route as TosLangRouteImport } from './routes/tos.$lang'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeServicoRoute = TermosDeServicoRouteImport.update({
  id: '/termos-de-servico',
  path: '/termos-de-servico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreatorRoute = AuthenticatedCreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MediakitIndexRoute = MediakitIndexRouteImport.update({
  id: '/mediakit/',
  path: '/mediakit/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediakitSlugRoute = MediakitSlugRouteImport.update({
  id: '/mediakit/$slug',
  path: '/mediakit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyLangRoute = PrivacyLangRouteImport.update({
  id: '/privacy/$lang',
  path: '/privacy/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const TosLangRoute = TosLangRouteImport.update({
  id: '/tos/$lang',
  path: '/tos/$lang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/links': typeof LinksRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/creator': typeof AuthenticatedCreatorRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/mediakit/$slug': typeof MediakitSlugRoute
  '/privacy/$lang': typeof PrivacyLangRoute
  '/tos/$lang': typeof TosLangRoute
  '/blogs/': typeof BlogsIndexRoute
  '/mediakit/': typeof MediakitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/links': typeof LinksRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/creator': typeof AuthenticatedCreatorRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/mediakit/$slug': typeof MediakitSlugRoute
  '/privacy/$lang': typeof PrivacyLangRoute
  '/tos/$lang': typeof TosLangRoute
  '/blogs': typeof BlogsIndexRoute
  '/mediakit': typeof MediakitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/links': typeof LinksRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/creator': typeof AuthenticatedCreatorRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/mediakit/$slug': typeof MediakitSlugRoute
  '/privacy/$lang': typeof PrivacyLangRoute
  '/tos/$lang': typeof TosLangRoute
  '/blogs/': typeof BlogsIndexRoute
  '/mediakit/': typeof MediakitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/links'
    | '/politica-de-privacidade'
    | '/termos-de-servico'
    | '/admin'
    | '/change-password'
    | '/creator'
    | '/blogs/$slug'
    | '/mediakit/$slug'
    | '/privacy/$lang'
    | '/tos/$lang'
    | '/blogs/'
    | '/mediakit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/links'
    | '/politica-de-privacidade'
    | '/termos-de-servico'
    | '/admin'
    | '/change-password'
    | '/creator'
    | '/blogs/$slug'
    | '/mediakit/$slug'
    | '/privacy/$lang'
    | '/tos/$lang'
    | '/blogs'
    | '/mediakit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/links'
    | '/politica-de-privacidade'
    | '/termos-de-servico'
    | '/_authenticated/admin'
    | '/_authenticated/change-password'
    | '/_authenticated/creator'
    | '/blogs/$slug'
    | '/mediakit/$slug'
    | '/privacy/$lang'
    | '/tos/$lang'
    | '/blogs/'
    | '/mediakit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LinksRoute: typeof LinksRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TermosDeServicoRoute: typeof TermosDeServicoRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  MediakitSlugRoute: typeof MediakitSlugRoute
  PrivacyLangRoute: typeof PrivacyLangRoute
  TosLangRoute: typeof TosLangRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  MediakitIndexRoute: typeof MediakitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-servico': {
      id: '/termos-de-servico'
      path: '/termos-de-servico'
      fullPath: '/termos-de-servico'
      preLoaderRoute: typeof TermosDeServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator': {
      id: '/_authenticated/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof AuthenticatedCreatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediakit/': {
      id: '/mediakit/'
      path: '/mediakit'
      fullPath: '/mediakit/'
      preLoaderRoute: typeof MediakitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediakit/$slug': {
      id: '/mediakit/$slug'
      path: '/mediakit/$slug'
      fullPath: '/mediakit/$slug'
      preLoaderRoute: typeof MediakitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/$lang': {
      id: '/privacy/$lang'
      path: '/privacy/$lang'
      fullPath: '/privacy/$lang'
      preLoaderRoute: typeof PrivacyLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tos/$lang': {
      id: '/tos/$lang'
      path: '/tos/$lang'
      fullPath: '/tos/$lang'
      preLoaderRoute: typeof TosLangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCreatorRoute: typeof AuthenticatedCreatorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCreatorRoute: AuthenticatedCreatorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LinksRoute: LinksRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TermosDeServicoRoute: TermosDeServicoRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  MediakitSlugRoute: MediakitSlugRoute,
  PrivacyLangRoute: PrivacyLangRoute,
  TosLangRoute: TosLangRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  MediakitIndexRoute: MediakitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
