/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LinksRouteImport } from './routes/links'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedCreatorRouteImport } from './routes/_authenticated/creator'
import { Route as MediakitIndexRouteImport } from './routes/mediakit.index'
import { Route as MediakitSlugRouteImport } from './routes/mediakit.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreatorRoute = AuthenticatedCreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MediakitIndexRoute = MediakitIndexRouteImport.update({
  id: '/mediakit/',
  path: '/mediakit/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediakitSlugRoute = MediakitSlugRouteImport.update({
  id: '/mediakit/$slug',
  path: '/mediakit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/links': typeof LinksRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/creator': typeof AuthenticatedCreatorRoute
  '/mediakit/$slug': typeof MediakitSlugRoute
  '/mediakit/': typeof MediakitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/links': typeof LinksRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/creator': typeof AuthenticatedCreatorRoute
  '/mediakit/$slug': typeof MediakitSlugRoute
  '/mediakit': typeof MediakitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/links': typeof LinksRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/creator': typeof AuthenticatedCreatorRoute
  '/mediakit/$slug': typeof MediakitSlugRoute
  '/mediakit/': typeof MediakitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/links'
    | '/admin'
    | '/change-password'
    | '/creator'
    | '/mediakit/$slug'
    | '/mediakit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/links'
    | '/admin'
    | '/change-password'
    | '/creator'
    | '/mediakit/$slug'
    | '/mediakit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/links'
    | '/_authenticated/admin'
    | '/_authenticated/change-password'
    | '/_authenticated/creator'
    | '/mediakit/$slug'
    | '/mediakit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LinksRoute: typeof LinksRoute
  MediakitSlugRoute: typeof MediakitSlugRoute
  MediakitIndexRoute: typeof MediakitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator': {
      id: '/_authenticated/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof AuthenticatedCreatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/mediakit/': {
      id: '/mediakit/'
      path: '/mediakit'
      fullPath: '/mediakit/'
      preLoaderRoute: typeof MediakitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediakit/$slug': {
      id: '/mediakit/$slug'
      path: '/mediakit/$slug'
      fullPath: '/mediakit/$slug'
      preLoaderRoute: typeof MediakitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCreatorRoute: typeof AuthenticatedCreatorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCreatorRoute: AuthenticatedCreatorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LinksRoute: LinksRoute,
  MediakitSlugRoute: MediakitSlugRoute,
  MediakitIndexRoute: MediakitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
