/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LinksRouteImport } from './routes/links'
import { Route as MediakitIndexRouteImport } from './routes/mediakit.index'
import { Route as MediakitSlugRouteImport } from './routes/mediakit.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const MediakitIndexRoute = MediakitIndexRouteImport.update({
  id: '/mediakit/',
  path: '/mediakit/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediakitSlugRoute = MediakitSlugRouteImport.update({
  id: '/mediakit/$slug',
  path: '/mediakit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/links': typeof LinksRoute
  '/mediakit/$slug': typeof MediakitSlugRoute
  '/mediakit/': typeof MediakitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/links': typeof LinksRoute
  '/mediakit/$slug': typeof MediakitSlugRoute
  '/mediakit': typeof MediakitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/links': typeof LinksRoute
  '/mediakit/$slug': typeof MediakitSlugRoute
  '/mediakit/': typeof MediakitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/links' | '/mediakit/$slug' | '/mediakit/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/links' | '/mediakit/$slug' | '/mediakit'
  id: '__root__' | '/' | '/auth' | '/links' | '/mediakit/$slug' | '/mediakit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LinksRoute: typeof LinksRoute
  MediakitSlugRoute: typeof MediakitSlugRoute
  MediakitIndexRoute: typeof MediakitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediakit/': {
      id: '/mediakit/'
      path: '/mediakit'
      fullPath: '/mediakit/'
      preLoaderRoute: typeof MediakitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediakit/$slug': {
      id: '/mediakit/$slug'
      path: '/mediakit/$slug'
      fullPath: '/mediakit/$slug'
      preLoaderRoute: typeof MediakitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LinksRoute: LinksRoute,
  MediakitSlugRoute: MediakitSlugRoute,
  MediakitIndexRoute: MediakitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
