DO $$
BEGIN
  CREATE TYPE public.social_platform AS ENUM ('youtube', 'instagram', 'tiktok', 'twitch', 'twitter');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS public.social_connections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  talent_id uuid NOT NULL REFERENCES public.talents(id) ON DELETE CASCADE,
  platform public.social_platform NOT NULL,
  profile_url text,
  handle text,
  external_account_id text,
  sync_enabled boolean NOT NULL DEFAULT true,
  current_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_synced_at timestamptz,
  last_sync_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (talent_id, platform)
);

CREATE TABLE IF NOT EXISTS public.social_metric_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connection_id uuid NOT NULL REFERENCES public.social_connections(id) ON DELETE CASCADE,
  metrics jsonb NOT NULL,
  captured_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS social_connections_sync_idx
  ON public.social_connections (platform, sync_enabled)
  WHERE sync_enabled;

CREATE INDEX IF NOT EXISTS social_metric_snapshots_connection_captured_idx
  ON public.social_metric_snapshots (connection_id, captured_at DESC);

DROP TRIGGER IF EXISTS update_social_connections_updated_at ON public.social_connections;
CREATE TRIGGER update_social_connections_updated_at
BEFORE UPDATE ON public.social_connections
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.social_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_metric_snapshots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Published social metrics are public" ON public.social_connections;
CREATE POLICY "Published social metrics are public"
  ON public.social_connections
  FOR SELECT
  TO anon, authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.talents
      WHERE talents.id = social_connections.talent_id
        AND talents.status = 'published'
    )
  );

DROP POLICY IF EXISTS "Admins can manage social connections" ON public.social_connections;
CREATE POLICY "Admins can manage social connections"
  ON public.social_connections
  FOR ALL
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

DROP POLICY IF EXISTS "Admins can read social metric history" ON public.social_metric_snapshots;
CREATE POLICY "Admins can read social metric history"
  ON public.social_metric_snapshots
  FOR SELECT
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

GRANT SELECT ON public.social_connections TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.social_connections TO authenticated;
GRANT SELECT ON public.social_metric_snapshots TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.social_metric_snapshots_id_seq TO authenticated;
GRANT ALL ON public.social_connections, public.social_metric_snapshots TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.social_metric_snapshots_id_seq TO service_role;

INSERT INTO public.social_connections (talent_id, platform, profile_url, handle)
SELECT
  talent.id,
  social.platform::public.social_platform,
  social.profile_url,
  NULLIF(
    trim(BOTH '@' FROM regexp_replace(split_part(social.profile_url, '?', 1), '^.*/', '')),
    ''
  )
FROM public.talents AS talent
CROSS JOIN LATERAL (
  VALUES
    ('youtube', talent.youtube_url),
    ('instagram', talent.instagram_url),
    ('tiktok', talent.tiktok_url),
    ('twitch', talent.twitch_url),
    ('twitter', talent.twitter_url)
) AS social(platform, profile_url)
WHERE social.profile_url IS NOT NULL
  AND social.profile_url <> ''
ON CONFLICT (talent_id, platform) DO UPDATE
SET
  profile_url = EXCLUDED.profile_url,
  handle = COALESCE(public.social_connections.handle, EXCLUDED.handle);

COMMENT ON TABLE public.social_connections IS
  'Server-managed social account identifiers and the latest normalized metrics for each talent.';

COMMENT ON TABLE public.social_metric_snapshots IS
  'Append-only history of normalized social metrics used for trend reporting.';
