-- Operational foundation for the redesigned Gamerbiz admin center.

ALTER TABLE public.lead_submissions
  ADD COLUMN IF NOT EXISTS pipeline_stage text NOT NULL DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS priority text NOT NULL DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS next_action_at timestamptz,
  ADD COLUMN IF NOT EXISTS internal_notes text,
  ADD COLUMN IF NOT EXISTS estimated_value numeric(12, 2),
  ADD COLUMN IF NOT EXISTS source text,
  ADD COLUMN IF NOT EXISTS tags text[] NOT NULL DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

DO $$
BEGIN
  ALTER TABLE public.lead_submissions
    ADD CONSTRAINT lead_submissions_pipeline_stage_check
    CHECK (pipeline_stage IN ('new', 'qualified', 'meeting', 'proposal', 'negotiation', 'won', 'lost'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.lead_submissions
    ADD CONSTRAINT lead_submissions_priority_check
    CHECK (priority IN ('low', 'normal', 'high', 'urgent'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS lead_submissions_pipeline_idx
  ON public.lead_submissions (pipeline_stage, priority, created_at DESC);

DROP TRIGGER IF EXISTS update_lead_submissions_updated_at ON public.lead_submissions;
CREATE TRIGGER update_lead_submissions_updated_at
BEFORE UPDATE ON public.lead_submissions
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE IF NOT EXISTS public.admin_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  summary text NOT NULL,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_audit_logs_created_idx
  ON public.admin_audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS admin_audit_logs_entity_idx
  ON public.admin_audit_logs (entity_type, entity_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.admin_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  severity text NOT NULL DEFAULT 'info',
  title text NOT NULL,
  message text NOT NULL,
  entity_type text,
  entity_id text,
  read_at timestamptz,
  resolved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  ALTER TABLE public.admin_notifications
    ADD CONSTRAINT admin_notifications_severity_check
    CHECK (severity IN ('info', 'warning', 'critical', 'success'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS admin_notifications_open_idx
  ON public.admin_notifications (resolved_at, created_at DESC);

CREATE TABLE IF NOT EXISTS public.social_sync_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  trigger_source text NOT NULL DEFAULT 'admin',
  requested_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  connection_ids uuid[] NOT NULL DEFAULT '{}'::uuid[],
  processed integer NOT NULL DEFAULT 0,
  succeeded integer NOT NULL DEFAULT 0,
  failed integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'running',
  results jsonb NOT NULL DEFAULT '[]'::jsonb,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

DO $$
BEGIN
  ALTER TABLE public.social_sync_runs
    ADD CONSTRAINT social_sync_runs_status_check
    CHECK (status IN ('running', 'completed', 'partial', 'failed'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS social_sync_runs_started_idx
  ON public.social_sync_runs (started_at DESC);

CREATE TABLE IF NOT EXISTS public.site_content (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  content_key text NOT NULL,
  locale text NOT NULL DEFAULT 'pt-BR',
  title text,
  description text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'draft',
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (content_key, locale)
);

DO $$
BEGIN
  ALTER TABLE public.site_content
    ADD CONSTRAINT site_content_status_check
    CHECK (status IN ('draft', 'published', 'archived'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DROP TRIGGER IF EXISTS update_site_content_updated_at ON public.site_content;
CREATE TRIGGER update_site_content_updated_at
BEFORE UPDATE ON public.site_content
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.admin_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_sync_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can read audit logs"
  ON public.admin_audit_logs FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can manage notifications"
  ON public.admin_notifications FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can read sync runs"
  ON public.social_sync_runs FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Published site content is public"
  ON public.site_content FOR SELECT TO anon, authenticated
  USING (status = 'published' OR public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can manage site content"
  ON public.site_content FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

GRANT SELECT ON public.admin_audit_logs, public.social_sync_runs TO authenticated;
GRANT ALL ON public.admin_notifications, public.site_content TO authenticated;
GRANT SELECT ON public.site_content TO anon;
GRANT ALL ON public.admin_audit_logs, public.admin_notifications, public.social_sync_runs, public.site_content TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.admin_audit_logs_id_seq, public.admin_notifications_id_seq TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.capture_admin_audit()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  entity jsonb;
  entity_id text;
BEGIN
  entity := CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
  entity_id := COALESCE(entity ->> 'id', entity ->> 'user_id', entity ->> 'talent_id');

  INSERT INTO public.admin_audit_logs (
    actor_id, action, entity_type, entity_id, summary, before_data, after_data
  ) VALUES (
    auth.uid(),
    lower(TG_OP),
    TG_TABLE_NAME,
    entity_id,
    TG_OP || ' em ' || TG_TABLE_NAME,
    CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) END
  );
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'talents', 'blog_posts', 'lead_submissions', 'creator_talent_access',
    'user_roles', 'site_content', 'social_connections'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS capture_admin_audit ON public.%I', table_name);
    EXECUTE format(
      'CREATE TRIGGER capture_admin_audit AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.capture_admin_audit()',
      table_name
    );
  END LOOP;
END $$;

REVOKE ALL ON FUNCTION public.capture_admin_audit() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.notify_admin_operations()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_TABLE_NAME = 'lead_submissions' AND TG_OP = 'INSERT' THEN
    INSERT INTO public.admin_notifications (
      severity, title, message, entity_type, entity_id
    ) VALUES (
      'info',
      CASE WHEN NEW.kind = 'brand' THEN 'Nova oportunidade de marca' ELSE 'Nova candidatura de creator' END,
      NEW.name || ' enviou uma nova resposta pelo site.',
      'lead_submissions',
      NEW.id::text
    );
  ELSIF TG_TABLE_NAME = 'social_connections'
    AND TG_OP = 'UPDATE'
    AND NEW.connection_status = 'error'
    AND OLD.connection_status IS DISTINCT FROM NEW.connection_status THEN
    INSERT INTO public.admin_notifications (
      severity, title, message, entity_type, entity_id
    ) VALUES (
      'critical',
      'Falha de sincronização',
      'Uma conexão de ' || NEW.platform::text || ' entrou em estado de erro.',
      'social_connections',
      NEW.id::text
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notify_admin_new_lead ON public.lead_submissions;
CREATE TRIGGER notify_admin_new_lead
AFTER INSERT ON public.lead_submissions
FOR EACH ROW EXECUTE FUNCTION public.notify_admin_operations();

DROP TRIGGER IF EXISTS notify_admin_connection_error ON public.social_connections;
CREATE TRIGGER notify_admin_connection_error
AFTER UPDATE ON public.social_connections
FOR EACH ROW EXECUTE FUNCTION public.notify_admin_operations();

REVOKE ALL ON FUNCTION public.notify_admin_operations() FROM PUBLIC, anon, authenticated;

INSERT INTO public.site_content (content_key, locale, title, description, status, published_at)
VALUES
  ('homepage', 'pt-BR', 'Página inicial', 'Hero, soluções, números e chamada final', 'published', now()),
  ('cases', 'pt-BR', 'Cases', 'Cases apresentados na página inicial', 'published', now()),
  ('clients', 'pt-BR', 'Clientes e parceiros', 'Logos de marcas e times', 'published', now()),
  ('footer', 'pt-BR', 'Rodapé', 'Links, contato e informações institucionais', 'published', now()),
  ('legal', 'pt-BR', 'Conteúdo jurídico', 'Política de privacidade e termos de serviço', 'published', now())
ON CONFLICT (content_key, locale) DO NOTHING;